### ISSUE TITLE
How to Mock?

### ISSUE THREAD

**Issue by adrianpaiva1** [openai-php/laravel#10]
How can I mock the facade or underlying class in tests?

Because the underlying OpenAI client (and other classes) are 'final' I'm unable to use mocking. 

I've tried with the standard Laravel facade mocking

`
OpenAi::shouldReceive('completions')->andReturn([])
`

Am I missing something simple here? is there a way to mock API calls without wrapping all API calls in my own methods?

**Comment by nunomaduro** [comment]
The example you provided should work.

**Comment by benswinburne** [comment]
When using the example above

    use OpenAI\Laravel\Facades\OpenAI;

    OpenAI::shouldReceive('completions')->andReturn([]);

The following error is returned

> The class \OpenAI\Client is marked final and its methods cannot be replaced. Classes marked final can be passed in to \Mockery::mock() as instantiated objects to create a partial mock, but only if the mock is not subject to type hinting checks.

I also tried mocking `OpenAI\Client` replacing the instance in the service container, but that class is also marked final so I get the same issue.

```
$this->instance(
    OpenAI::class,
    Mockery::mock(OpenAI::class, function ($mock) {
        $mock
            ->shouldReceive('completions')
            ->once()
            ->andReturn(['...']);
    })
);
```

Presumably I'm missing something. As it stands I'm just having to work around it using my own method as a wrapper, then mocking my own method to remove the call to OpenAI,

```
use OpenAI\Laravel\Facades\OpenAI;

class MockableOpenAI
{
    public function completions($prompt)
    {
        return OpenAI::completions()->create([
            'model' => 'text-davinci-003',
            'prompt' => $prompt,
        ]);
    }
}

...

$this->instance(
    MockableOpenAI::class,
    Mockery::mock(MockableOpenAI::class, function ($mock) {
        $mock
            ->shouldReceive('completions')
            ->once()
            ->andReturn(['OpenAI Output']);
    })
);
```

**Comment by ianvizarra** [comment]
@adrianpaiva1 @benswinburne 
Try this
```php
$this->swap(Client::class, new \Mockery());
OpenAI::shouldReceive('completions')->andReturnSelf();
OpenAI::shouldReceive('create')->andReturn([
    'choices' => [['text' => 'test']],
    'usage' => []
]);
```

**Comment by Punksolid** [comment]
It didn't work for me neither,  I will follow the same approach as @benswinburne. In my case if I could mock `ThreadRunResponse` it will be good enough I think.

**Comment by Punksolid** [comment]
@benswinburne I just found a solution that worked perfectly for me. 

https://tomasvotruba.com/blog/2019/03/28/how-to-mock-final-classes-in-phpunit
https://github.com/dg/bypass-finals

Regards
