### ISSUE TITLE
[Bug]: Meta information not included in CreateResponse

### ISSUE THREAD

**Issue by birdhouses** [openai-php/laravel#102]
The meta information is not on the CreateResponse object. I could not find how to obtain the metainformation on a ChatCompletion response in the documentation.

Getting the metainformation only works for legacy `completions`, not for Chat

```  
$client = \OpenAI::client(env('OPENAI_API_KEY'));


$response = $client->chat()->create([
                    'model' => $model,
                    'temperature' => 0,
                    'top_p' => 0,
                    'messages' => [
                        [
                            "role" => "user",
                            "content" => $generatedPrompt->prompt
                        ]
                    ],
                ]);

Log::info(json_encode($response->meta()));
```

`Call to undefined method OpenAI\Responses\Chat\CreateResponse::meta() {"userId":1,"exception":"[object] (Error(code: 0): Call to undefined method OpenAI\\Responses\\Chat\\CreateResponse::meta()`

```
        "openai-php/laravel": "^0.6.3",
        "php": "^8.1",
```

**Comment by gehrisandro** [comment]
Hi @birdhouses 

Please upgrade to the latest version, it is available there.
