### ISSUE TITLE
Undefined array key "file_id"

### ISSUE THREAD

**Issue by ckefalianou** [openai-php/laravel#116]
I am using the library, sending a **text** and some **image_url** as content.
After retrieving the Assistant, creating a Thread, I create a Message:

`        [
            'role' => 'user',
            'content' => [
                [
                    'type' => 'text',
                    'text' => $prompt['title']
                ],
                [
                    'type' => 'image_url',
                    'image_url' => [
                        'url' => $photo[0]->large,
                        'detail' => 'high',
                    ],
                ],
                [
                    'type' => 'image_url',
                    'image_url' => [
                        'url' => $photo[1]->large,
                        'detail' => 'high',
                    ],
                ],
            ]
        ];
`

Thank you in advance!

**Comment by gehrisandro** [comment]
Fixed
