### ISSUE TITLE
New GPT API Endpoints.

### ISSUE THREAD

**Issue by peterthomson** [openai-php/laravel#16]
The newly available GPT API doesn't use the 'completions' endpoint. What's the easiest way for us to use the GPT compliant end points ? It looks like the 'client' package which is more general php is pretty close to being updated. Should those of us on the Laravel package switch or are the two packages wrapper / synced?

**Comment by nunomaduro** [comment]
Done: https://twitter.com/enunomaduro/status/1631221339028684802?s=20.
