### ISSUE TITLE
Mocking in Tests any suggestions?

### ISSUE THREAD

**Issue by alnutile** [openai-php/laravel#22]
Typically I can mock a facade like this

```php
    public function test_gets_data() {
        $user = User::factory()->create();
        $data = get_fixture("barbershop_results.json");
        OpenAI::shouldReceive('completions->create')
            ->once()
            ->andReturn($data);

        $this->actingAs($user)->post(route('examples.ask'), [
            'question' => "PHP Is"
        ])
            ->assertStatus(200);
    }
```
but I am getting this error.

`Mockery\Exception: The class \OpenAI\Client is marked final and its methods cannot be replaced. Classes marked final can be passed in to \Mockery::mock() as instantiated objects to create a partial mock, but only if the mock is not subject to type hinting checks.`

Any suggestions? Sorry if obvious but if not then I will commit a PR to update the README.md to help the next person.

Thanks for the library

**Comment by stevebauman** [comment]
@alnutile Also see https://github.com/openai-php/client/issues/77 if you need an immediate work around for testing.
