### ISSUE TITLE
How can i do for support stream in laravel？

### ISSUE THREAD

**Issue by 915880683** [openai-php/laravel#28]
How can i do for support stream in laravel？
i try this  but maybe  something went wrong

    return response([
      'text'=>$result
    ] )->header('Content-type', 'text/event-stream')
    ->header('Cache-Control', 'no-cache');

**Comment by jhull** [comment]
Thank you so much for adding this. Much cleaner than what I had before, BUT - how do you stream back the response? Is it the same server-sent events idea with echo, etc. - or is there a cleaner way through Laravel?

**Comment by gehrisandro** [comment]
@jhull Here is an example:

```php
  $client = OpenAI::client('sk-**********');

  $stream = $client->completions()->createStreamed([
      'model' => 'text-davinci-003',
      'prompt' => 'PHP is ',
      'max_tokens' => 1000,
  ]);

  return response()->stream(
      function () use ($stream) {
          foreach($stream as $response){
              echo $response->choices[0]->text;
              ob_flush();
              flush();
          }
      },
      200,
      [
          'X-Accel-Buffering' => 'no',
      ]
  );
  ```
