### ISSUE TITLE
Call to undefined method of OpenAI::completions()

### ISSUE THREAD

**Issue by eirworks** [openai-php/laravel#33]
In version `0.4.2` using any methods like completions, images, chats not working and throws `Call to undefined method of OpenAI::xxxxx()`. Reverting back to 0.4.1 seems solving it. This was tested in fresh laravel install.

Laravel version: 10.0
PHP: 8.1
OpenAI-laravel: 0.4.2

**Comment by nunomaduro** [comment]
Fixed on `0.4.3`.
