### ISSUE TITLE
OpenAI API Errors when Streaming Chat Completions

### ISSUE THREAD

**Issue by PaulWen** [openai-php/laravel#35]
Hi, thank you for providing such a nice library!

I am currently using the streamed chat interface `OpenAI::chat()->createStreamed([...]);` and I was wondering if there is any way to capture error messages in case the OpenAI API returns an error like this:

```
{
    "error": {
        "message": "The model `gpt-3.5-turboo` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
```

Currently, it looks to me like the stream is only closed immediately but no exception seems to be thrown in case of an error.

**Comment by pMatt1988** [comment]
@PaulWen It looks like you're trying to use the model "gpt-3.5-turboo". Try to use "gpt-3.5-turbo"instead.

**Comment by PaulWen** [comment]
I am aware of what the error message means but I am **not getting it returned by this library**. Instead, I was calling the OpenAI endpoint directly to generate this error message.

I am expecting this library to either throw an exception that includes the error message returned by OpenAI or to offer an error handler/callback mechanism that allows me to react to errors.
