### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by bomshteyn** [openai-php/laravel#36]
Thank you for this great package!

I have been having a lot of jobs timing out with the following exception:
```
Symfony\Component\HttpClient\Exception\TimeoutException: Idle timeout reached for "https://api.openai.com/v1/chat/completions".
```

I see in the main PHP client there is a [method](https://github.com/openai-php/client/issues/39#issuecomment-1474334394) to set the timeout limit, how can this be set using the Laravel facade? Do you think that method will address the issue?

**Comment by youngbobby** [comment]
Hopefully, it can be resolved soon. Having Timeout issues a lot too.

**Comment by MaximeGratens** [comment]
Same

**Comment by JackWH** [comment]
There's a recent bug/misconfiguration with OpenAI servers, which is causing connections to terminate after exactly 5 minutes. If you're generating lengthy outputs (>≈1.5K tokens) with GPT-4, this might explain it: https://github.com/openai/openai-python/issues/399

This broke my integration, and has gone seemingly unnoticed by OpenAI for some time now... 😥

**Comment by gehrisandro** [comment]
@bomshteyn Please check if this is what you would expect: https://github.com/openai-php/laravel/pull/45

cc @youngbobby @MaximeGratens
