### ISSUE TITLE
Fakeable's buildAttributes doesn't play nicely with batch embeddings

### ISSUE THREAD

**Issue by nik-418** [openai-php/laravel#41]
The embeddings endpoint can take a batch of inputs. 

However, when trying to fake this in a test, only the first input in the batch is taken into account, the rest are ignored.

```php
OpenAI::fake([
            EmbeddingsCreateResponse::fake([
                'data' => [
                    [
                        'embedding' => [0.1, 0.2, 0.3], // only 0.1 and 0.2 are used; 0.3 is ignored
                    ],
                    [
                        'embedding' => [0.1, 0.2, 0.3], // this is completely ignored
                    ],
                ],
            ])
        ]);
```

This is due to the specific implementation of `buildAttributes`:
```php
foreach ($original as $key => $entry) {
            $new[$key] = is_array($entry) ?
                self::buildAttributes($entry, $override[$key] ?? []) :
                $override[$key] ?? $entry;
        }
```

This is a problem for tests because any downstream code won't have the correct number of items in the batch coming out of the fake.

**Comment by gehrisandro** [comment]
This is a known bug: https://github.com/openai-php/client/issues/122

Going to fix this as soon as I find time for. Feel free to make a PR if you want 🙏
