### ISSUE TITLE
Make organization configuration more clear

### ISSUE THREAD

**Issue by gehrisandro** [openai-php/laravel#48]
Make it more clear, that the organization ID is required, not the name.

-----

              Problem here lays in env variable naming. 
min openai is actually two similar things, one is called display name and other is called id. In env file in laravel mislead me kind of so I wrote Coding Wisely as organisation name, and when I removed it and changed to organisation id provided in openai, it worked. Maybe just update environment name to be clear that that is ID

Here is what i am talking about:
OPENAI_ORGANIZATION=
I would rename it to OPENAI_ORGANIZATION_ID and point user where to get it.

In openAI you have both open organization and open organization id that starts with org-....

_Originally posted by @nezaboravi in https://github.com/openai-php/laravel/issues/47#issuecomment-1593381125_

**Comment by alekmlynek** [comment]
I came searching for this comment because I have the exact question. Glad to know it is the ID.

**Comment by chris-hud** [comment]
These docs cost me about 10 minutes as well. This thread sent me in right direction
