### ISSUE TITLE
Idle timeout

### ISSUE THREAD

**Issue by elfeffe** [openai-php/laravel#57]
I had to use PHP OpenAi instead of this package and set:

```
\OpenAI::factory()
->withHttpClient(new Client(['timeout' => 90, 'connect_timeout' => 90]))
->withApiKey(config('openai.api_key'))
->make()->chat()->create([
'model' => $gptModel,
'messages' => [
         ['role' => 'user', 'content' => $data['prompt']],
],
'temperature' => (float)$data['temperature'],
'max_tokens' => (int)$data['max_tokens'],
]);
```
How can we set the timeout?
I'm using GPT-4, and it's usual to have this kind of error.
I think it's related https://github.com/openai-php/laravel/issues/36

**Comment by gehrisandro** [comment]
You can specify the timeout via the configuration file: https://github.com/openai-php/laravel#request-timeout
