### ISSUE TITLE
How can I use factory for Azure

### ISSUE THREAD

**Issue by DC-Sebastian** [openai-php/laravel#60]
Can i use 

`
$client = OpenAI::factory()
    ->withBaseUri('{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}')
    ->withHttpHeader('api-key', '{your-api-key}')
    ->withQueryParam('api-version', '{version}')
    ->make();
`

for Azure as described [here](https://github.com/openai-php/client#azure)?

I don't know exactly how to implement this with OpenAI PHP for Laravel.

**Comment by gehrisandro** [comment]
Hi @DC-Sebastian 

One way is to override the singleton in your service provider:

```php
$this->app->singleton(ClientContract::class, static function (): Client {
    $apiKey = config('openai.api_key');

    if (! is_string($apiKey)) {
        throw ApiKeyIsMissing::create();
    }

    return OpenAI::factory()
        ->withBaseUri('{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}')
        ->withHttpHeader('api-key', '{your-api-key}')
        ->withQueryParam('api-version', '{version}')
        ->withHttpClient(new \GuzzleHttp\Client(['timeout' => config('openai.request_timeout', 30)]))
        ->make();
});
```


Here is the original implementation from the package provided.
https://github.com/openai-php/laravel/blob/main/src/ServiceProvider.php#L24

Hope this helps.

**Comment by jpcaparas** [comment]
If extending the client contract, it's preferrable to use `extend` over `singleton`:

Below is a working example of an Azure OpenAI contract override:

```php
        $this->app->extend(ClientContract::class, static function (): OpenAIClient {
            $apiKey = config('openai.api_key');
            $resourceName = config('openai.azure.resource_name');
            $deploymentId = config('openai.azure.deployment_id');
            $version = config('openai.azure.version');

            if (! is_string($apiKey)) {
                throw ApiKeyIsMissing::create();
            }
            
            return OpenAI::factory()
                ->withBaseUri(sprintf('%s.openai.azure.com/openai/deployments/%s/', $resourceName, $deploymentId))
                ->withHttpHeader('api-key', $apiKey)
                ->withQueryParam('api-version', $version)
                ->withHttpClient(new HttpClient(['timeout' => config('openai.request_timeout', 30)]))
                ->make();
        });
 ```

Ensure that you put in the correct details down to the `api-version` otherwise, you'll get a `Resource not found` error.
