### ISSUE TITLE
Not working even after installing.

### ISSUE THREAD

**Issue by shahidkarimi** [openai-php/laravel#61]
Class "OpenAI\Laravel\Facades\OpenAI" not found

tried to use:
`\OpenAI\Laravel\Facades\OpenAI

\OpenAI\Laravel\Facades\OpenAI\OpenAI`

**Comment by haydar** [comment]
I cant get the what you try. Could you provide code?

**Comment by pb30** [comment]
Any change if you run `composer require openai-php/laravel:^0.7.0`

Can you share some example code where you are trying to use it?

**Comment by gbarrios9670** [comment]
I ran composer require openai-php/laravel
in a fresh instalation or laravel 10

**Comment by pb30** [comment]
Where are you seeing the error?

**Comment by gbarrios9670** [comment]
here is the code
![image](https://github.com/openai-php/laravel/assets/71102644/64c846ad-04db-42ef-87a4-7d7f312ba39d)
![image](https://github.com/openai-php/laravel/assets/71102644/8e43adac-0452-47ed-bb92-b937b276a5b8)
sometimes a get Class "OpenAI\Laravel\Facades\OpenAI" not found

**Comment by yslinear** [comment]
me too

**Comment by pb30** [comment]
> Unsupported operand types: string * int

Either set a value for OPENAI_REQUEST_TIMEOUT or comment it out. Issue occurs when it is left blank

-----

Could not reproduce Class Not Found error:

```
laravel new test
cd test
composer require openai-php/laravel
php artisan vendor:publish --provider="OpenAI\Laravel\ServiceProvider"
php artisan serve
```

```
use OpenAI\Laravel\Facades\OpenAI;
Route::get('/', function () {
    dd(OpenAI:: completions()->create([
                                          'model'  => 'text-davinci-003',
                                          'prompt' => 'PHP is']));
});
```
