### ISSUE TITLE
Getting error by using model " gpt-3.5-turbo " 

### ISSUE THREAD

**Issue by parvez301901** [openai-php/laravel#62]
It gives this error
" Undefined array key "choices" 

my code is:

$title = $request->youtube_title;

   $result = OpenAI::completions()->create([
            "model" => "gpt-3.5-turbo",
            "temperature" => 0.7,
            "top_p" => 1,
            "frequency_penalty" => 0,
            "presence_penalty" => 0,
            'max_tokens' => 500,
            'prompt' => sprintf('write a lesson plan on %s', $title),
     ]);

Can we find this out?

**Comment by parvez301901** [comment]
I have found the solution.

**Comment by tchoblond59** [comment]
Can you tell me how you figured it out please ?

**Comment by pb30** [comment]
If you're trying to use `gpt-3.5-turbo`, you need to use the Chat endpoint: https://github.com/openai-php/client#chat-resource
