### ISSUE TITLE
How to use HTTP Proxy?

### ISSUE THREAD

**Issue by yangfancn** [openai-php/laravel#64]
How to use HTTP Proxy or other GuzzleHttp Options? 
Can provide a method like OpenAi::requestOptions(['proxy' => 'http://...', ...])?

**Comment by gehrisandro** [comment]
Hi @yangfancn

You can do this by registering your own instance in you service container.

see https://github.com/openai-php/laravel/blob/main/src/ServiceProvider.php#L24
