### ISSUE TITLE
Fluent method to specify API key (multi tenancy)

### ISSUE THREAD

**Issue by binaryfire** [openai-php/laravel#69]
Hi guys

Is there a clean way to use multiple api keys with this package? Use case is a multi-tenant app where users supply their own keys

Overriding config values feels a bit hacky and doesn’t always work well with Octane.

**Comment by pb30** [comment]
Can always just use the underlying client https://github.com/openai-php/client

**Comment by binaryfire** [comment]
True. I’ll do that 👍

**Comment by clementmas** [comment]
I'd rather rely on this package's default configuration than copy/pasting it into my Laravel app.

Is there any way to access the client object to call the `withApiKey` method?
