### ISSUE TITLE
Tonen

### ISSUE THREAD

**Issue by pabloescobar42** [openai-php/laravel#7]
{
    "id": "cmpl-GERzeJQ4lvqPk8SkZu4XMIuR",
    "object": "text_completion",
    "created": 1586839808,
    "model": "text-davinci:003",
    "choices": [
        {
            "text": "\n\nThis is indeed a test",
            "index": 0,
            "logprobs": null,
            "finish_reason": "length"
        }
    ],
    "usage": {
        "prompt_tokens":99999
        "completion_tokens": 7,
        "total_tokens": 99999

    }
}

**Comment by c0nst4ntin** [comment]
Could you maybe elaborate a bit more on your Problem and how this came about?
