### ISSUE TITLE
OpenAI  \  Exceptions  \  UnserializableResponse  Syntax error

### ISSUE THREAD

**Issue by alxzhdanov** [openai-php/laravel#76]
Hello

PHP 8.2.3 
Laravel 10.32.1

I installed packet.
Copy example in controller. 
And get error. 
Cant find any solution. 

![image](https://github.com/openai-php/laravel/assets/23114004/d35f023e-fa1b-4bce-95ce-131871955b7b)

**Comment by gehrisandro** [comment]
Hi @alxzhdanov 

Maybe you are the API from an IP which is restriced by OpenAI?

see https://github.com/openai-php/client/issues/281
