### ISSUE TITLE
Question: JSON mode support?

### ISSUE THREAD

**Issue by petervandijck** [openai-php/laravel#82]
This is a question, feel free to delete is this is the wrong place.

Does the package support the recently launched JSON response_format mode? https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format

**Comment by gehrisandro** [comment]
Hi @petervandijck 

Yes it does. If you have any trouble using it, just let us know.

**Comment by CamilleScholtz** [comment]
Did you ever figure this out?

**Comment by damiam** [comment]
> Did you ever figure this out?

yes the code is as follows 

```
$chat = OpenAI::chat()->create([
    'model' => 'gpt-4o',
    'messages' => [...],
    'temperature' => $temperature,
    'response_format' => ['type' => 'json_object'],
]);
```
