### ISSUE TITLE
 ERROR  There are no commands defined in the "openai" namespace.

### ISSUE THREAD

**Issue by ruzzzz6312** [openai-php/laravel#83]
Hey guys, sorry to bother, but I can't install it

 ERROR  There are no commands defined in the "openai" namespace.

[ec2-user@ip-172-31-23-2 www]$ composer require openai-php/laravel
./composer.json has been updated
Running composer update openai-php/laravel
Loading composer repositories with package information
Updating dependencies
Lock file operations: 4 installs, 0 updates, 0 removals
  - Locking openai-php/client (v0.7.3)
  - Locking openai-php/laravel (v0.7.0)
  - Locking php-http/discovery (1.19.2)
  - Locking php-http/multipart-stream-builder (1.3.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Downloading php-http/discovery (1.19.2)
  - Downloading php-http/multipart-stream-builder (1.3.0)
  - Downloading openai-php/client (v0.7.3)
  - Downloading openai-php/laravel (v0.7.0)
  - Installing php-http/discovery (1.19.2): Extracting archive
  - Installing php-http/multipart-stream-builder (1.3.0): Extracting archive
  - Installing openai-php/client (v0.7.3): Extracting archive
  - Installing openai-php/laravel (v0.7.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.  

  inertiajs/inertia-laravel .................................................................................................... DONE
  irazasyed/telegram-bot-sdk ................................................................................................... DONE
  laravel/dusk ................................................................................................................. DONE
  laravel/sail ................................................................................................................. DONE
  laravel/sanctum .............................................................................................................. DONE
  laravel/tinker ............................................................................................................... DONE
  laravel/ui ................................................................................................................... DONE
  nesbot/carbon ................................................................................................................ DONE
  nunomaduro/collision ......................................................................................................... DONE
  nunomaduro/termwind .......................................................................................................... DONE
  openai-php/laravel ........................................................................................................... DONE
  simplesoftwareio/simple-qrcode ............................................................................................... DONE
  spatie/laravel-ignition ...................................................................................................... DONE

85 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force

   INFO  No publishable resources for tag [laravel-assets].  

No security vulnerability advisories found
Using version ^0.7.0 for openai-php/laravel
[ec2-user@ip-172-31-23-2 www]$ php artisan openai:install

   ERROR  There are no commands defined in the "openai" namespace.  

[ec2-user@ip-172-31-23-2 www]$ php -v
PHP 8.1.23 (cli) (built: Sep 15 2023 21:56:29) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.23, Copyright (c) Zend Technologies

**Comment by pb30** [comment]
Install command was added in [v0.8.1](https://github.com/openai-php/laravel/releases/tag/v0.8.1)

Try `composer require openai-php/laravel ^0.8.1`

**Comment by ruzzzz6312** [comment]
That helped, thanks @pb30
