### ISSUE TITLE
Upgrade openai-php/client package to latest version

### ISSUE THREAD

**Issue by Jimerson21** [openai-php/laravel#88]
Hello everyone,

In the current version it is not possible to obtain the object "usage" from ThreadRun.

Thank you.

**Comment by arnebr** [comment]
The library has been updated to v0.9, does that help you?

**Comment by gehrisandro** [comment]
Technically, it would already have worked, but I created a release and add the doc block to make it more clear:

https://github.com/openai-php/laravel/releases/tag/v0.9.1
