### ISSUE TITLE
Resource not found using Azure

### ISSUE THREAD

**Issue by KirillDakhnyuk** [openai-php/laravel#90]
I've tried a solution from #60, and every time I get a `Resource not found` error while creating a thread using OpenAI facade. 

<img width="983" alt="Screenshot 2024-03-06 at 18 09 02" src="https://github.com/openai-php/laravel/assets/21340376/7f355ad7-d0c1-492f-a60f-4d2513b834e2">

Thanks :)

**Comment by gehrisandro** [comment]
Hi @KirillDakhnyuk 

This is a problem on your Azure deployment.
