### ISSUE TITLE
Should support audio transcription at word level

### ISSUE THREAD

**Issue by ncpope** [openai-php/laravel#91]
Currently only supports segment based timestamps, word based timestamps are also available: https://platform.openai.com/docs/api-reference/audio/createTranscription

needs support for property of timestamp_granularities which is an array of strings

```
timestamp_granularities[]
array
Optional
Defaults to segment
```

**Comment by gehrisandro** [comment]
Support added a while ago: https://github.com/openai-php/client/releases/tag/v0.8.5
