### ISSUE TITLE
Error when use Assistant with stream

### ISSUE THREAD

**Issue by jsinoti** [openai-php/laravel#92]
When I define to use the OpenAI::threads()->createAndRun with stream true, I'm getting a error with de result parse.

`OpenAI\Exceptions\UnserializableResponse {#1453 ▼ // app/Helper/OpenIAHelper.php:43
  #message: "Syntax error"
  #code: 0
  #file: "
/xxxxxxx/vendor/openai-php/client/src/Transporters/HttpTransporter.php"
  #line: 63
  -previous: JsonException {#1416 ▼
    #message: "Syntax error"
    #code: 4
    #file: "
/xxxxxxx/vendor/openai-php/client/
src/Transporters/HttpTransporter.php"
    #line: 61
    trace: {▼
      
/xxxxxxx/vendor/openai-php/client/
src/Transporters/HttpTransporter.php:61 {▼
OpenAI\Transporters\HttpTransporter->requestObject(Payload $payload): Response …
        ›     /** @var array{error?: array{message: string, type: string, code: string}} $data */
        ›     $data = json_decode($contents, true, flags: JSON_THROW_ON_ERROR);
        › } catch (JsonException $jsonException) {
        arguments: {▼
          $json: """
            event: thread.created
            data: {"id":"thread_rICWuyxxxxxxxxxxaj","object":"thread","created_at":1712078109,"metadata":{}}
....            
`

**Comment by devgeek27** [comment]
This is because assistant V2 must be used. The library needs to be updated to pass v2 here:
 public function register(): void
    {
        $this->app->singleton(ClientContract::class, static function (): Client {
            $apiKey = config('openai.api_key');
            $organization = config('openai.organization');

            if (! is_string($apiKey) || ($organization !== null && ! is_string($organization))) {
                throw ApiKeyIsMissing::create();
            }

            return OpenAI::factory()
                ->withApiKey($apiKey)
                ->withOrganization($organization)
                ->withHttpHeader('OpenAI-Beta', 'assistants=**v2**')
                ->withHttpClient(new \GuzzleHttp\Client(['timeout' => config('openai.request_timeout', 30)]))
                ->make();
        });

        $this->app->alias(ClientContract::class, 'openai');
        $this->app->alias(ClientContract::class, Client::class);
    }

**Comment by gehrisandro** [comment]
Stream support has been added (no need for API v2).

https://github.com/openai-php/laravel/releases/tag/v0.9.0
