### ISSUE TITLE
Support change of endpoint url to support OctoAI

### ISSUE THREAD

**Issue by DivByZeroIT** [openai-php/laravel#94]
Sorry if this is OT or a dumb question, is it possible to add the endpoint URL as a config parameter (or change it when making calls in other ways) to make calls to providers like OctoAI that support the same OpenAI API standard with just a different set of endpoints / keys ?

Thanks

**Comment by willcastillo** [comment]
Hey @DivByZeroIT , for what it's worth, the base package open-ai-php/client in its [factory library](https://github.com/openai-php/client/blob/main/src/Factory.php#L102) exposes a method called `withBaseUri` which allows you to specify the base uri for every call.

**Comment by nekhbet** [comment]
$client = OpenAI::factory()
    ->withBaseUri('{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}')
    ->withHttpHeader('api-key', '{your-api-key}')
    ->withQueryParam('api-version', '{version}')
    ->make();

**Comment by DivByZeroIT** [comment]
Thanks @willcastillo @willcastillo !
