### ISSUE TITLE
Add support for Assistant API V2

### ISSUE THREAD

**Issue by devgeek27** [openai-php/laravel#96]
Hey could  you please add support for Assistant V2 API to use the latest OpenAI API features.

Thank you.

**Comment by afzafri** [comment]
The updates for base package will comes soon https://github.com/openai-php/client/issues/381#issuecomment-2075609987

**Comment by gehrisandro** [comment]
Release for assistants v2 has arrived (beta). 🚀

https://github.com/openai-php/laravel/releases/tag/v0.10.0-beta.1
