### ISSUE TITLE
[Improvements] Support for Batch API

### ISSUE THREAD

**Issue by vesselind** [openai-php/laravel#97]
Hello,

Do you plan on adding support for the new Batch OpenAI API?
https://platform.openai.com/docs/guides/batch

Thank you!

**Comment by arnebr** [comment]
Is now implemented in v0.9.1 of the base client library, will be updated soon to this library, correct @gehrisandro?

**Comment by gehrisandro** [comment]
Made a new release, even it would have worked before: https://github.com/openai-php/laravel/releases/tag/v0.9.1
