### ISSUE TITLE
Fine Tunes endpoint is deprecated

### ISSUE THREAD

**Issue by cimd** [openai-php/laravel#98]
Hi,

The old v1 fine tunes endpoint has been deprecated: 
https://platform.openai.com/docs/deprecations/2023-08-22-fine-tunes-endpoint

Any plans to update the library adding the new endpoint?

**Comment by gehrisandro** [comment]
Release for assistants v2 has arrived (beta). 🚀

https://github.com/openai-php/laravel/releases/tag/v0.10.0-beta.1
