### ISSUE TITLE
How can I use Theads with stream?

### ISSUE THREAD

**Issue by muriloeliaseinov** [openai-php/laravel#99]
Hello friends,

I looked for the same question and couldn't find it, it may seem silly, but I would really appreciate it if someone could help me.

In the openaiphp project there is an example of how to call a thead with the stream option. (https://github.com/openai-php/client?tab=readme-ov-file#create-streamed-2)

Is there a way to do this through Laravel's openai-php library?

I tried the following way but it gave me an error.

               $stream  = OpenAI::threads()->runs()->create(
                    threadId: $aiAssistentCheck->thread_external_id,
                    parameters: [
                        'assistant_id' => $aiAssistentCheck->external_id,
                        'additional_instructions' => $aiAssistentCheck->additional_instructions,
                        'stream ' => true,
                    ],
                );
                
Within runs() the createStreamed option did not appear as it did in chat()->createStreamed

Thank you for your attention

**Comment by gehrisandro** [comment]
Hi @muriloeliaseinov 

There is a `->threads()->runs()->createStreamed()` function.

Are you using the latest version?
